name: Build and Push Docker DDHub Replicator image

on:
  workflow_dispatch:
  #push:
    #branches: [ "main" ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Build Service Docker image
      run: docker build --file "${{ github.workspace }}/DWIS.OpenLab.DDHubReplicator/Dockerfile" --tag digiwells/dwisopenlabddhubreplicator:stable .

    - name: Login to DockerHub
      run: docker login -u="${{ secrets.DOCKERHUB_USERNAME }}" -p="${{ secrets.DOCKERHUB_PASSWORD }}"
        
    - name: Push images to DockerHub
      run: |
        docker push digiwells/dwisopenlabddhubreplicator:stable
